#!/bin/bash
# Copyright 2020 Frédéric Wang. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

cd `dirname $(realpath $0)`
java -jar score-date.jar
